### ISSUE TITLE
移动端实时视频的背景替换

### ISSUE THREAD

**Issue by dyfcode** [yeyupiaoling/ChangeHumanBackground#1]
作者你好，想问下基于图片的背景替换能做移动端实时视频的背景替换吗？有什么思路吗？

**Comment by roybill** [comment]
@yeyupiaoling   你好,我最近也在研究这方面的东西,请问你找到实现方法了吗?

**Comment by yeyupiaoling** [comment]
在Android，我还没有研究过。
